version: "3.8"
services:
  nginx:
    restart: always
    image: nginx:alpine
    container_name: go-nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8087:8080"
      - "4433:443"
    extra_hosts:
      - "base.test:127.0.0.1"
      - "base.local:127.0.0.1"
  go:
    restart: always
    container_name: go-base
    build:
      context: ./
      target: dev
      dockerfile: ./docker/go/Dockerfile
    depends_on:
      - nginx
      - postgresql
    volumes:
      - .:/go/src/github.com/pokervarino27/go-base
    ports:
      - 8080:8080
    env_file:
      - ./configs/dev/dev.env
  postgresql:
    image: postgres:latest
    container_name: gobase-postgresql
    env_file:
      - ./configs/database/postgresql.dev.env
    ports:
      - 5432:5432

networks:
  default:
    external:
      name: docker_default